# HPC用户管理系统 - 管理员配置
# 定义哪些用户是系统管理员

# 系统管理员配置
admins:
  - username: "zhang_wei"         # 从LDAP用户中指定的管理员
    full_name: "张伟"
    email: "zhang.wei@hpc.university.edu"
    auth_type: "ldap"             # LDAP认证
    role: "super_admin"           # 超级管理员
    uid_number: 10001             # 来自LDAP的uidNumber

  - username: "li_ming"           # 从LDAP用户中指定的普通管理员
    full_name: "李明"
    email: "li.ming@hpc.university.edu"
    auth_type: "ldap"
    role: "admin"                 # 普通管理员
    uid_number: 10002             # 来自LDAP的uidNumber
    permissions:                  # 权限列表
      - "user_management"
      - "role_assignment"

# 管理员权限定义
permissions:
  user_management:
    description: "用户管理权限"
    actions:
      - "view_users"
      - "assign_roles"
      - "manage_groups"
      - "sync_ldap"
  
  role_assignment:
    description: "角色分配权限"
    actions:
      - "assign_pi_role"
      - "assign_student_role"
      - "manage_student_pi_relations"
  
  system_admin:
    description: "系统管理权限"
    actions:
      - "manage_admins"
      - "system_config"
      - "backup_restore"
  
  view_statistics:
    description: "统计查看权限"
    actions:
      - "view_user_stats"
      - "view_group_stats"
      - "export_reports"
  
  view_logs:
    description: "日志查看权限"
    actions:
      - "view_audit_logs"
      - "view_sync_logs"
      - "view_system_logs"

# 默认权限配置
default_permissions:
  super_admin:                    # 超级管理员默认拥有所有权限
    - "user_management"
    - "role_assignment"
    - "system_admin"
    - "view_statistics"
    - "view_logs"
  
  admin:                          # 普通管理员默认权限
    - "user_management"
    - "view_statistics"
    - "view_logs"

# 自动初始化配置
auto_init:
  enable: true                    # 是否自动初始化管理员
  force_password_reset: true      # 强制首次登录修改密码
  default_password_policy:        # 密码策略
    min_length: 8
    require_uppercase: true
    require_lowercase: true  
    require_numbers: true
    require_special_chars: false